[package]
name = "taranis"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["fmt", "env-filter", "chrono", "json", "registry"] }
tracing-appender = "0.2"
tokio-websockets = "0.11"
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"
toml = "0.8"
chrono = {version = "0.4", features = ["serde"]}